name: Create TIL/Bookmark from Issue

on:
  issues:
    types: [opened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    if: github.actor == github.repository_owner
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Create TIL markdown file from issue
        uses: actions/github-script@v7
        id: create-til
        with:
          retries: 3
          script: |
            const script = require('.github/workflows/write.js')
            await script({ github, context, core, require })

      - name: Commit and push TIL file
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add ./src/content/bookmarks/*.mdx
          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git commit -m "bookmark/til: add content from #${{ github.event.issue.number }} [automated]"
            echo "Commit created."
          fi

      - name: Push changes to repository
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref_name }}

      - name: Close Issue
        if: success()
        run: gh issue close --comment "Bookmark/TIL created and pushed. Auto-closing issue." "${{ github.event.issue.number }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
